version: "3.9"
services:

  nginx:
    container_name: web
    image: traefik/whoami:latest

  varnish:
    container_name: varnish
    image: varnish:latest
    command: ["-a :8800,PROXY"]
    volumes:
      - "./varnish/default.vcl:/etc/varnish/default.vcl:ro"

  traefik:
    image: "traefik:v2.4.8"
    container_name: "traefik"
    command:
      - "--configfile=/etc/traefik/traefik.yaml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.127.0.0.1.nip.io`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./dynamic/:/dynamic/
      - ./config/:/etc/traefik/
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
