version: "3.8"

services:
  traefik:
    image: "traefik:v2.5"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=dynamic.yaml
      - --accesslog
      - --accesslog.format=json
      - --api
      - --log.level=DEBUG
    labels:
      traefik.enable: "true"
      traefik.http.routers.api.rule: Host(`d.127.0.0.1.nip.io`)
      traefik.http.routers.api.service: api@internal
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./dynamic.yaml:/dynamic.yaml"
      - "./certs/:/etc/traefik/certs/"
