apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: whoami-http
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-redirectscheme@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: w.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: whoami-svc
              servicePort: 80
