apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik-internal
  rules:
    - host: whoami.213.189.52.253.nip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: whoami-svc
              servicePort: 80
