name: Traefik use-cases
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose -f basic-docker-compose/docker-compose.yaml up -d
      - name: Whoami Service
        run: curl -s --retry 10 --retry-connrefused http://whoami.127.0.0.1.nip.io:8080/
      - name: Traefik API
        run: curl -s --retry 10 --retry-connrefused http://dashboard.127.0.0.1.nip.io:8080/api/version
      - name: Traefik Dashboard
        run: curl -s retry 10 --retry-connrefused http://dashboard.127.0.0.1.nip.io:8080/dashboard/
